POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Prepare for interview",
  "description": "Review Java and Spring Boot",
  "status": "TODO"
}

###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/tasks/1

###
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "title": "Prepare for interview",
  "description": "Finished Spring Boot review",
  "status": "DONE"
}


###
DELETE http://localhost:8080/api/tasks/1




### Test 1 - Valid task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Learn Validation",
  "description": "Practice Spring Boot validation",
  "status": "DONE"
}

### Test 2 - Empty title
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "",
  "description": "test",
  "status": "TODO"
}

### Test 3 - Blank title
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "   ",
  "description": "test",
  "status": "TODO"
}

### Test 4 - Missing title
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "description": "test",
  "status": "TODO"
}

### Test 5 - Title longer than 100 characters
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "description": "test",
  "status": "TODO"
}

### Test 6 - Description longer than 500 characters
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Valid title",
  "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "status": "TODO"
}


### 1. Exisiting Task
GET http://localhost:8080/api/tasks/1

### 2. NON-EXISTING Task
GET http://localhost:8080/api/tasks/999999

### 3. new Task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Test exception handling",
  "description": "Regression test",
  "status": "TODO"
}

### 4. illegal Task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "",
  "description": "Invalid task",
  "status": "TODO"
}

### 5. update Task
PUT http://localhost:8080/api/tasks/3
Content-Type: application/json

{
  "title": "Test exception handling",
  "description": "Regression test",
  "status": "DONE"
}


###
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "Job Search"
}


###
GET http://localhost:8080/api/projects

### Existing Project
GET http://localhost:8080/api/projects/1

### Non-existing Project
GET http://localhost:8080/api/projects/999

###
POST http://localhost:8080/api/projects/1/tasks
Content-Type: application/json

{
  "title": "Learn Spring Boot",
  "description": "Practice REST APIs",
  "status": "DONE"
}

### Create Task
POST http://localhost:8080/api/projects/1/tasks
Content-Type: application/json

{
  "title": "Learn DTO",
  "description": "Practice Request and Response DTOs",
  "status": "TODO"
}


### Invalid Task
POST http://localhost:8080/api/projects/1/tasks
Content-Type: application/json

{
  "title": "",
  "description": "Invalid task",
  "status": "TODO"
}


### Project with tasks
GET http://localhost:8080/api/projects/1

### Project without tasks
GET http://localhost:8080/api/projects/2/tasks

### Project does not exist
GET http://localhost:8080/api/projects/999/tasks

###
POST http://localhost:8080/api/projects/1/tasks
Content-Type: application/json

{
  "title": "",
  "description": "Invalid task",
  "status": "TODO"
}



### day6
GET http://localhost:8080/api/tasks

###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Practice DTO Refactoring",
  "description": "Refactor TaskController",
  "status": "DONE"
}

###
PUT http://localhost:8080/api/tasks/11
Content-Type: application/json

{
  "title": "DTO Refactoring Completed",
  "description": "Testing PUT endpoint",
  "status": "DONE"
}


###for project
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "API Refactoring"
}

###
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": ""
}


###
GET http://localhost:8080/api/projects